fix(atomic): use compatTokenClass not tokenClass
Compilation error: tokenClass variable doesn't exist, should be
compatTokenClass that was defined earlier in the method.

r26.1